id: A4C6E4C48
title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
type: translation
pechas:
- I66223C26
- I5B1AFA18
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:40.123562
  last_modified_at: 2023-01-04 11:33:40.123576
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I66223C26/D76A: FB5C
  I5B1AFA18/A4B9: FB5C
